[package]
name = "crawler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solcrawl = { path = "../../solcrawl", version = "0.1.0" }
solana-client = "1.10.3"