[package]
name = "solcrawl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-client = "1.10.3"
solana-sdk = "1.10.3"
solana-program = "1.10.3"
solana-transaction-status = "1.10.3"